# Generated by Django 5.2.10 on 2026-01-10 02:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('day_type', models.CharField(choices=[('show', 'Show Day'), ('travel', 'Travel Day'), ('off', 'Day Off'), ('rehearsal', 'Rehearsal')], max_length=16)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(blank=True, default='', max_length=64)),
                ('tz', models.CharField(default='America/Los_Angeles', max_length=64)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address1', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(blank=True, default='', max_length=64)),
                ('postal', models.CharField(blank=True, default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.day')),
            ],
            options={
                'ordering': ['role', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('last_edited_by', models.CharField(blank=True, default='', max_length=128)),
                ('last_edited_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.day')),
            ],
            options={
                'ordering': ['-last_edited_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('role_title', models.CharField(blank=True, default='', max_length=128)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('permission', models.CharField(choices=[('owner', 'owner'), ('edit', 'edit'), ('read', 'read')], default='read', max_length=16)),
                ('connected', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='core.group')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='core.tour')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.tour'),
        ),
        migrations.AddField(
            model_name='day',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='core.tour'),
        ),
        migrations.AddField(
            model_name='day',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='days', to='core.venue'),
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_local', models.TimeField(blank=True, null=True)),
                ('end_local', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('todo', 'todo'), ('done', 'done')], default='todo', max_length=16)),
                ('associations', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.day')),
            ],
            options={
                'ordering': ['start_local', 'name'],
                'indexes': [models.Index(fields=['day', 'start_local'], name='core_schedu_day_id_ee7c53_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('tour', 'name')},
        ),
        migrations.AddIndex(
            model_name='day',
            index=models.Index(fields=['tour', 'date'], name='core_day_tour_id_7cc9e4_idx'),
        ),
    ]
