# Generated by Django 5.2.10 on 2026-01-12 00:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_templates', to='core.tour')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleTemplateEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('start_local', models.CharField(blank=True, default='', max_length=5)),
                ('end_local', models.CharField(blank=True, default='', max_length=5)),
                ('notes', models.TextField(blank=True, default='')),
                ('associations', models.JSONField(blank=True, default=list)),
                ('start_tz', models.CharField(blank=True, default='', max_length=64)),
                ('end_tz', models.CharField(blank=True, default='', max_length=64)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.scheduletemplate')),
            ],
        ),
    ]
