# Generated by Django 5.2.10 on 2026-01-12 01:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_scheduletemplate_scheduletemplateevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address1', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=80)),
                ('postal', models.CharField(blank=True, default='', max_length=40)),
                ('place_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('source', models.CharField(blank=True, default='db', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='core.tour')),
            ],
        ),
        migrations.CreateModel(
            name='DayLodging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in_iso', models.DateTimeField(blank=True, null=True)),
                ('check_out_iso', models.DateTimeField(blank=True, null=True)),
                ('rooms', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lodging', to='core.day')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_lodgings', to='core.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='DayLodgingGuest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lodging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='core.daylodging')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lodging_guests', to='core.person')),
            ],
            options={
                'indexes': [models.Index(fields=['lodging', 'person'], name='core_daylod_lodging_c19493_idx')],
                'unique_together': {('lodging', 'person')},
            },
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['tour', 'name'], name='core_hotel_tour_id_8d9132_idx'),
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['place_id'], name='core_hotel_place_i_328af9_idx'),
        ),
    ]
