# Generated by Django 5.2.10 on 2026-01-12 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_hotel_daylodging_daylodgingguest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='color',
            field=models.CharField(default='red', max_length=32),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tour'),
        ),
    ]
