# Generated by Django 5.2.10 on 2026-01-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_group_color_alter_group_name_alter_group_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='aftershow',
            field=models.TextField(blank=True, default=''),
        ),
    ]
