# Generated by Django 5.2.10 on 2026-01-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_day_aftershow'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='visibility',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
